development:
  bucket_name: myapp_development
  access_key_id: AKIAJXO6C643UVGS3POQ
  secret_access_key: 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

test:
  bucket_name: myapp_test
  access_key_id: AKIAJXO6C643UVGS3POQ
  secret_access_key: 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

production:
  bucket_name: myapp
  access_key_id: AKIAJXO6C643UVGS3POQ
  secret_access_key: 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